### ISSUE TITLE
m68000 is 24 bit

### ISSUE THREAD

**Issue by wrigjl** [wrigjl/binaryninja-m68k#1]
The early M68k's (M68000, M68010, probably all M680[01][0-9]) had a 24bit address space. Accessing addresses > 0xffffff are equivalent to accessing address & 0xffffff (i.e. the uppermost byte of the address is completely ignored).

To fix this, we need to modify all of the Op* handling to set the width of the address arithmetic to 3 bytes (24 bits).

**Comment by wrigjl** [comment]
5d67476631873dbcd9dacb0db43ddc1e27f2cae2 implements this for OpAbsolute()

**Comment by lab313ru** [comment]
So, is it fixed?

**Comment by wrigjl** [comment]
I think so, at least the person I know who was looking at sega genesis roms was happy.

**Comment by lab313ru** [comment]
I'm such a person too.:)

пн, 20 апр. 2020 г. в 17:45, Jason L. Wright <notifications@github.com>:

**Comment by wrigjl** [comment]
you two should talk:
https://zznop.com/2019/12/08/fuzzing-sega-genesis-emulators/

**Comment by lab313ru** [comment]
Ah, I know that guy!

пн, 20 апр. 2020 г. в 17:52, Jason L. Wright <notifications@github.com>:

**Comment by psifertex** [comment]
So this issue should be closed, right?

**Comment by wrigjl** [comment]
Yup... I am just a slacker

**Comment by psifertex** [comment]
No worries. Need me to submit a PR for the s/is 4/== 4/ as well? 😛

**Comment by wrigjl** [comment]
Na, got it.
