### ISSUE TITLE
Release for integration into repository manager?

### ISSUE THREAD

**Issue by psifertex** [wrigjl/binaryninja-m68k#3]
Given that the upstream version appears abandoned, would you be willing to cut a release so that we can integrate your fork into the community plugin repository?  More details on the process are available at: 

https://binary.ninja/2019/07/04/plugin-manager-2.0.html

**Comment by psifertex** [comment]
Uhh, this already exists and I'm slow. 😛

**Comment by wrigjl** [comment]
TBH, this version is almost abandoned... the project that had me hacking m68k pretty heavily ended about 9 months ago =) I'm having a fire sale on this codebase.
