### ISSUE TITLE
broken on python3.8

### ISSUE THREAD

**Issue by psifertex** [wrigjl/binaryninja-m68k#4]
https://github.com/wrigjl/binaryninja-m68k/blob/master/__init__.py#L969

Should probably be `== 4` I believe.

**Comment by lab313ru** [comment]
Yes. And I also have problems with this module. It occupies all PC's RAM.

**Comment by psifertex** [comment]
That's probably worth filing a separate issue for. :-)

**Comment by wrigjl** [comment]
thanks for the fix, @psifertex. I suppose I need to figure out the binja incantation for doing a release.
